name: xxz python ci test 

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags.'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       if: ${{ always() }}
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-west-2

#     - name: CodeGuru Reviewer
#       uses: aws-actions/codeguru-reviewer@v1.1
#       with:
#         s3_bucket: codeguru-reviewer-github-xxz-test # S3 Bucket with "codeguru-reviewer-*" prefix

    - name: Upload Generated Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sarif_results
        path: sample.sarif.json
        
#     # Step 3: Upload results into GitHub
    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: sample.sarif.json
